import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Inter, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/NavbarDemo";

// const inter = Inter({ subsets: ["latin"] });
const sourceSans = Source_Sans_3({ subsets: ['latin']})

export const metadata: Metadata = {
  title: "Nilam Packers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <NavbarDemo />
        </ThemeProvider>
      </body>
    </html>
  );
}
